// Generated by CoffeeScript 1.7.1
(function() {
  describe('$.jQueryFormSerializer.regexp', function() {
    describe('simple', function() {
      beforeEach(function() {
        return this.regexp = $.jQueryFormSerializer.regexp.simple;
      });
      it('should match against simple field names', function() {
        return expect('simple_field').to.match(this.regexp);
      });
      return it('should not match against array field names', function() {
        return expect('array_field[]').to.not.match(this.regexp);
      });
    });
    return describe('array', function() {
      beforeEach(function() {
        return this.regexp = $.jQueryFormSerializer.regexp.array;
      });
      it('should match against array field names', function() {
        return expect('array_field[]').to.match(this.regexp);
      });
      return it('should not match against simple field names', function() {
        return expect('simple_field').to.not.match(this.regexp);
      });
    });
  });

}).call(this);
