// Generated by CoffeeScript 1.7.1
(function() {
  var document, jsdom, sinonChai;

  if (typeof window !== "undefined" && window !== null) {
    window.expect = chai.expect;
  } else if (typeof global !== "undefined" && global !== null) {
    jsdom = require('jsdom').jsdom;
    document = jsdom('<html><head></head><body></body></html>');
    global.window = document.createWindow();
    global.sinon = require('sinon');
    global.chai = require('chai');
    global.expect = chai.expect;
    sinonChai = require("sinon-chai");
    chai.use(sinonChai);
    global.$ = global.jQuery = require('jquery');
    require('../../jquery.form.serializer');
  }

}).call(this);
